### ISSUE TITLE
Clean feedback page

### ISSUE THREAD

**Issue by Fishdigger** [itec4750-team2/ITEC-4750-Team2-Site-Reordered#10]

**Comment by mm0426** [comment]
My plan is to add some client side validation to both the faculty and student feedback pages.  Currently; the results are emailed to a nonexistent email address and the (for lack of a better term) interested parties are hard coded into the HTML.  The email results might be an elegant solution; however I feel that a future portion of the project should be to replace the hard coded HTML with a dynamic drop down list populated by results from a database query.

**Comment by mm0426** [comment]
Added some client validation to faculty and student feedback pages to verify valid email address entry and that the comment section was populated when appropriate.  Also updated the "To whom should your feedback be sent?" section to replace the members from the team from last semester with our team members.
