### ISSUE TITLE
Create registration page

### ISSUE THREAD

**Issue by Fishdigger** [itec4750-team2/ITEC-4750-Team2-Site-Reordered#5]
When a teacher signs up maybe it could generate a key or something for them to give to students to use when they sign up maybe? Would have to figure out a way for that to work with multiple courses though.

**Comment by Fishdigger** [comment]
@sarahgoodman712 Can you create markup for this page and we'll add logic later.

**Comment by sarahgoodman712** [comment]
Will do! :)
