### ISSUE TITLE
Create course management pages

### ISSUE THREAD

**Issue by Fishdigger** [itec4750-team2/ITEC-4750-Team2-Site-Reordered#7]
- Open only to admins and the owning professor
- Should be able to do all CRUD actions

**Comment by Kateknm** [comment]
Joe, I'm sorry I didn't see that you assigned this to yourself...
I think my latest commits might have overstepped you here. : ( 
Feel free to re-do it your way.

**Comment by bigjoe7022** [comment]
No worries - I will re branch & go from there. I am being a little slow out of the gate on this. :)

**Comment by Kateknm** [comment]
I believe this issue can be closed. There are some issues to tweak but mostly done.

**Comment by bigjoe7022** [comment]
Oops - forgot I had assigned this to myself - I will close it now
